In [ ]:
from sklearn.cluster import DBSCAN
import numpy as np

In [ ]:
X= np.array([
    [1,2],[2,2],[2,3],
    [8,7],[8,8],[7,8],
    [50,50]
])

In [ ]:
X

array([[ 1,  2],
       [ 2,  2],
       [ 2,  3],
       [ 8,  7],
       [ 8,  8],
       [ 7,  8],
       [50, 50]])

In [ ]:
dbscan = DBSCAN(eps=1.5, min_samples=2)

In [ ]:
dbscan.fit(X)

DBSCAN(eps=1.5, min_samples=2)

In [ ]:
print(dbscan.labels_)

[ 0  0  0  1  1  1 -1]

In [ ]:
data = {
    'Base Salary':[50000,60000,55000],
    'Bonus' : [5000,7000,3000],
    'Stock Options' : [10000,15000,12000],
    'Year at Company' : [1,3,2]
}
data

{'Base Salary': [50000, 60000, 55000],
 'Bonus': [5000, 7000, 3000],
 'Stock Options': [10000, 15000, 12000],
 'Year at Company': [1, 3, 2]}

In [ ]:
import pandas as pd
df = pd.DataFrame(data)
df

   Base Salary  Bonus  Stock Options  Year at Company
0        50000   5000          10000                1
1        60000   7000          15000                3
2        55000   3000          12000                2

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=2)
pca_result = pca.fit_transform(df)

In [ ]:
pca_result

array([[-5403.32885509,  1117.35523815],
       [ 5950.97463749,   834.87302927],
       [ -547.64578241, -1952.22826742]])

In [ ]:
df_pca = pd.DataFrame(pca_result, columns=['PC1','PC2'])

In [ ]:
df_pca

           PC1          PC2
0 -5403.328855  1117.355238
1  5950.974637   834.873029
2  -547.645782 -1952.228267

In [ ]:
import pandas as pd
from sklearn.decomposition import PCA

data = {
    'Base Salary':[50000,60000,55000],
    'Bonus' : [5000,7000,3000],
    'Stock Options' : [10000,15000,12000],
    'Year at Company' : [1,3,2]
}
df = pd.DataFrame(data)
pca = PCA(n_components=3)
pca_result = pca.fit_transform(df)
df_pca = pd.DataFrame(pca_result, columns=['PC1','PC2','PC3'])
df_pca

           PC1          PC2           PC3
0 -5403.328855  1117.355238 -5.630000e-13
1  5950.974637   834.873029 -5.630000e-13
2  -547.645782 -1952.228267 -5.630000e-13

In [ ]:
x = 10
print(type(x))

<class 'int'>

In [ ]:
print(isinstance(x, int))

True

In [ ]:
x = "test"
print(isinstance(x, int))

False

In [ ]:
name = "Dhiraj"
print(isinstance(name, str))

True

In [ ]:
my_list = [1, 2, 3]
print(isinstance(my_list, list))

True

In [ ]:
value = 100.5
if isinstance(value, float):
    print("It's a float number.")
else:
    print("It's not a float number.")

It's a float number.

In [ ]:
value = "5"
print(isinstance(value, (int, str)))

True

In [ ]:
print("2+3")

In [ ]:
inp = eval(input("Enter input:"))
print(inp)

Enter input:2+4
6

In [ ]:
x = 10
y = 20
code = "x + y"
answer = eval(code)
print(answer)

30

In [ ]:
user_input = "2 \* 3 + 4"
result = eval(user_input)
print(result)

<>:1: SyntaxWarning: invalid escape sequence '\*'
<>:1: SyntaxWarning: invalid escape sequence '\*'
/tmp/ipykernel_5881/2032281737.py:1: SyntaxWarning: invalid escape sequence '\*'
  user_input = "2 \* 3 + 4"

SyntaxError: unexpected character after line continuation character (<string>, line 1)